export const GET_ACTIVE_PROFILE = "GET_ACTIVE_PROFILE";
export const OPEN_BIOGRAPHY_COMPONENT = "OPEN_BIOGRAPHY_COMPONENT";
export const CLOSE_BIOGRAPHY_COMPONENT = "CLOSE_BIOGRAPHY_COMPONENT";
export const OPEN_MULTIMEDIA_COMPONENT = "OPEN_MULTIMEDIA_COMPONENT";
export const CLOSE_MULTIMEDIA_COMPONENT = "CLOSE_MULTIMEDIA_COMPONENT";
